### ISSUE TITLE
🛠️  Setup next.js app

### ISSUE THREAD

**Issue by ghost** [RasCarlito/carlogren#1]
## Tasks

- [x] Latest node.js
- [x] Use create-next-app
- [ ] Write basic readme
- [ ] Choose color scheme

### Color scheme

- https://coolors.co/ccdbdc-80ced7-63c7b2-8e6c88-263d42
- https://coolors.co/aeffd8-8affc1-8fdc97-ac8887-9f4a54
- https://coolors.co/f79256-fbd1a2-7dcfb6-00b2ca-1d4e89
- https://coolors.co/f7c59f-2a324b-767b91-c7ccdb-e1e5ee
